database:
  port: 3306
  host: "127.0.0.1"
  user: "minecraft"
  password: "minecraft"
  database: "minecraft"
bot-token: ""
xapi-token: ""

link:
  max-accounts-linked: 3
  link-expiration: 300
  unlink-expiration: 120

# Servidor de Discord
discord-guild: "442668326888669195"
discord-guild-url: "https://discord.edoras.es/"
member-role: "442669542465077249"

# Canales de texto
link-channel: "695992710699679794"
log-channel: "708762845428449351"

# Canales excluidos del borrado de mensajes
channels-excluded-from-purge:
  - 442679780886708224
  - 442679874109308928
  - 1005503769414484008